name: The E-Team DJs
favicon: null
layout_spectrum: 0.24965
typography_spectrum: 0.07143
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The E-Team DJ and Photo Booth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#19ffff'
    - '#191b1a'
    - '#ff97fe'
    - '#ff2523'
  brandStrength: 0
  lightness: 0.3148936
  saturation: 0.9182603
  rhythmicContrast: 0.4829787
purpose: []
