layout_spectrum: 0
color:
  saturation: 0.9182603
  lightness: 0.3148936
  brandStrength: 0.8319149
  brandColors:
    - '#040403'
    - '#FEFEFE'
    - '#5C5B43'
    - '#BD42E9'
    - '#1E66D7'
  rhythmicContrast: 0.4829787
typography_spectrum: 0.09361702
name: The E-Team DJs
